<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net481;net9.0</TargetFrameworks>
    <AssemblyName>HAgent.Storage.File</AssemblyName>
    <RootNamespace>HAgent.Storage.File</RootNamespace>
    <PackageId>HAgent.Storage.File</PackageId>
    <Version>0.1.8</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HAgent.Core\HAgent.Core.csproj" />
    <PackageReference Include="System.Text.Json" Version="10.0.11" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
  </ItemGroup>
</Project>
